### ISSUE TITLE
2.1.1 Installing R, tools, and examples (typo)

### ISSUE THREAD

**Issue by IZE85** [WinVector/PDSwR2#1]
In the second edition of your book, on page 20 in the subsection 2.1.1, there is a typo in the following sentence:

"We suggest you **_follows_** the steps in section A.1 of appendix A to install R, packages, tools, and the book examples."

"follow" instead of "follows"

**Comment by JohnMount** [comment]
Sorry about that, and thank you for reporting it. I'll get that back into errata so possible reprints may not have that typo.
