### ISSUE TITLE
5.1.1 Subsetting rows and columns (Taking care when using data.table) typo?

### ISSUE THREAD

**Issue by IZE85** [WinVector/PDSwR2#2]
In the example "Taking care when using data.table" in the subsection "5.1.1 Subsetting rows and columns" there is a comment regarding the code that says "Notice that this returns the column x much like **_d$x_** would."

Maybe you wanted it that way, but eventually you meant "[...] much like **_df_**$x would.".

**Comment by JohnMount** [comment]
Sorry about that, and thank you for reporting it. We will try and get that into the errata.
