### ISSUE TITLE
6.2.5 Evaluating probability models, mistake in Figure 6.19

### ISSUE THREAD

**Issue by IZE85** [WinVector/PDSwR2#3]
In section "6.2.5 Evaluating probability models", I believe there is a slight mistake in Figure 6.19 on page 193.

The second line in the Figure for "match (not spam)" has a probability of "0.02".

The contribution then is depicted as "contribution : (1-0) * log(1-0.98) = -0.02".

I believe, it should actually say "contribution : (1-0) * log(1-**_0.02_**) = -0.02".

**Comment by JohnMount** [comment]
Thank you, we will look into this.
